export const GET_EMPLOYEE_SUBORDINATES = 'GET_EMPLOYEE_SUBORDINATES';
export const SET_EMPLOYEE_SUBORDINATES = 'SET_EMPLOYEE_SUBORDINATES';
export const SEARCH_EMPLOYEE_BY_NAME = 'SEARCH_EMPLOYEE_BY_NAME';
export const GET_EMPLOYEE_FAILED= 'GET_EMPLOYEE_FAILED';
